<?php

/**
 * this file includes all of the widgets
 * that live in this dir.
 * If you add a new widget, you should add it here.
 *
 * $Id: includes.inc 3130 2008-08-12 14:07:41Z mpwalsh8 $
 *
 * @author Walter A. Boring IV <waboring@newsblob.com>
 * @package phpHtmlLib
 * 
 */ 

include_once(PHPHTMLLIB_ABSPATH . "/widgets/svg/SVGDocumentClass.inc");
include_once(PHPHTMLLIB_ABSPATH . "/widgets/svg/SVGGraph.inc");

?>
