<?php

/**
 * this file includes all of the widgets
 * that live in this dir.
 * If you add a new widget, you should add it here.
 *
 * $Id: includes.inc 3130 2008-08-12 14:07:41Z mpwalsh8 $
 *
 * @author Walter A. Boring IV <waboring@newsblob.com>
 * @package phpHtmlLib
 * 
 */ 

/**
 * do the includes
 *
 * commented widgets are not really ready for 
 * prime time.
 *
 */
include_once(PHPHTMLLIB_ABSPATH . "/widgets/data_list/DataList.inc");
include_once(PHPHTMLLIB_ABSPATH . "/widgets/data_list/DataListSource.inc");
include_once(PHPHTMLLIB_ABSPATH . "/widgets/data_list/DefaultGUIDataList.inc");

?>
