<?php

/**
 * Holds the old ContainerWidget
 *
 * $Id: ContainerWidget.inc 1444 2005-05-12 01:24:05Z hemna $
 * 
 * @author Walter A. Boring IV <waboring@newsblob.com>
 * @package phpHtmlLib
 * 
 */


/**
 * This is just to maintain 
 * compatibility with the
 * 1.1.0 release of phphtmllib
 *
 * @author Walter A. Boring IV <waboring@newsblob.com>
 * @package phpHtmlLib 
 * @deprecated
 */
class ContainerWidget extends Container {
}
?>
